
package javadb;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author 71IH
 */
 class event_confirm extends javax.swing.JFrame {


     private Connection con;
     private Statement stm;
     private ResultSet rs;
     String name;
    public event_confirm(String name) 
    {
       this.name=name;
         try
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/s?autoReconect=true&useSSL=false","root","varu1234");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Event Request Response");

        jLabel2.setText("Date :");

        jLabel3.setText("Venue :");

        jButton1.setText("Confirm Event");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel Event");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton1)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) 
    {                                         
        // TODO add your handling code here:
            String date=jTextField1.getText();
            String ven=jTextField2.getText();
             try {
                  Statement stm1=con.createStatement();
             ResultSet req=stm1.executeQuery("Select * from event_request");
              while(req.next())
              {
                 if(req.getString("Event_Name").equals(name))
                 {
                      
                      String str="insert into event (Event_Name, Subject, Class_Priority, Date, venue)" + " values(?,?,?,?,?)";
                      PreparedStatement preparedStmt = con.prepareStatement(str);
                      //preparedStmt.setInt(1,3);
                       preparedStmt.setString (1, name);
                       preparedStmt.setString (2, req.getString("Subject") );
                       preparedStmt.setString (3, req.getString("Class_Priority"));
                       preparedStmt.setString (4, date);
                       preparedStmt.setString (5, ven);
                       preparedStmt.executeUpdate();
                        String createString =
                       "create table " +name+
                       " (Student_id varchar(10) NOT NULL, STUDENT_NAME varchar(40) NOT NULL,PRIMARY KEY(Student_id))";
                        stm1=con.createStatement();
                        stm1.execute(createString);
                        deletequery(req);
                       dispose();
                 }
              }                
        }
        catch (SQLException e) {
            Logger.getLogger(EventReqe.class.getName()).log(Level.SEVERE, null, e);
            dispose();}
        
    }      
     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {  
             try {
                  stm=con.createStatement();
              rs=stm.executeQuery("Select * from event_request");
              while(rs.next())
              {
                 if(rs.getString("Event_Name").equals(name))
                      deletequery(rs);
     }
              }
             catch (SQLException e) {
            Logger.getLogger(EventReqe.class.getName()).log(Level.SEVERE, null, e);
            }
             dispose();
     }
    /**
     * @param args the command line arguments
     */
    void deletequery(ResultSet rs)
    {
      
         try {
                 String sql=" Delete from event_request where Event_Name = ?";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,rs.getString("Event_Name"));
                ps.executeUpdate();
             }
          catch (SQLException ex) {
             Logger.getLogger(event_confirm.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    void panel() {
        
      // jTextField1.setText(name);
      
            
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(event_request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(event_request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(event_request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(event_request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    setVisible(true);
                    
                }
            });
        } 
        //</editor-fold>
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}

public class event_request
{
    public event_request(String name)
    {
        
        event_confirm e=new event_confirm(name);
        e.panel();
        e.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
}